pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://google.bintray.com/flexbox-layout" }
        maven {
            url "https://raw.githubusercontent.com/signalapp/maven/master/aesgcmprovider/release/"
            content {
                includeGroupByRegex("org\\.signal.*")
            }
        }
        maven {
            url "https://repo1.maven.org/maven2/com/goterl/lazysodium-android"
            content {
                includeGroupByRegex "com\\.goterl.*"
            }
        }
        maven { url "https://jitpack.io" }
        /*maven {
            url "https://raw.github.com/signalapp/maven/master/photoview/releases/"
            content {
                includeGroupByRegex "com\\.github\\.chrisbanes.*"
            }
        }
        maven {
            url "https://raw.github.com/signalapp/maven/master/shortcutbadger/releases/"
            content {
                includeGroupByRegex "me\\.leolin.*"
            }
        }
        maven {
            url "https://raw.github.com/signalapp/maven/master/circular-progress-button/releases/"
            content {
                includeGroupByRegex "com\\.github\\.dmytrodanylyk\\.circular-progress-button\\.*"
            }
        }
        maven {
            url "https://raw.github.com/signalapp/maven/master/sqlcipher/release/"
            content {
                includeGroupByRegex "org\\.signal.*"
            }
        }*/
    }
}

rootProject.name = "bchat-android"

include ':app'
include ':libsession'
include ':libsignal'
include ':stickyheader'