package com.thoughtcrimes.securesms.compose_utils

import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

val TextColor = Color(0xFFEBEBEB)
val TextColorLight = Color(0xFF333333)
val BackgroundColor = Color(0xFF11111A)
val Primary = Color(0xFF1C1C26)
val PrimaryLight = Color(0xFFF0F0F0)
val OnPrimary = Color(0xFFFFFFFF)
val Background = Color(0xFF1C1C26)
val BackgroundLight = Color(0xFFF0F0F0)
val OnBackgroundLight = Color(0xFF333333)
val Outline = Color(0xFF4B4B64)
val OutlineLight = Color(0xFFA7A7BA)
val SurfaceLight = Color(0xFFF8F8F8)

class Colors(
    val primaryButtonColor: Color,
    val secondaryButtonColor: Color,
    val backgroundColor: Color,
    val secondaryContentColor: Color,
    val editTextPlaceholder: Color,
    val textFieldFocusedColor: Color,
    val textFieldUnfocusedColor: Color,
    val textFieldCursorColor: Color,
    val textFieldTextColor: Color,
    val tertiaryButtonColor: Color,
    val disabledPrimaryButtonContentColor: Color,
    val onMainContainerTextColor: Color,
    val secondaryTextColor: Color,
    val editTextBackground: Color,
    val editTextColor: Color,
    val editTextHint: Color,
    val titleTextColor: Color,
    val iconColor: Color,
    val beldexAddressColor: Color,
    val cardBackground: Color,
    val iconTint: Color,
    val changeLogColor: Color,
    val changeLogBackground: Color,
    val lockTimerColor: Color,
    val unCheckedSwitchThumb: Color,
    val switchTrackColor: Color,
    val settingsCardBackground: Color,
    val dialogBackground: Color,
    val restoreDescColor: Color,
    val seedInfoTextColor: Color,
    val actionIconBackground: Color,
    val createButtonBackground: Color,
    val contactCardBackground: Color,
    val contactCardBorder: Color,
    val requestCountBackground: Color,
    val requestCountColor: Color,
    val searchBackground: Color,
    val inputHintColor: Color,
    val disabledButtonContainerColor: Color,
    val disabledButtonContent: Color,
    val textFieldDescriptionColor: Color,
    val cancelButtonTextColor: Color,
    val textColor: Color,
    val walletInfoHighlightColor: Color,
    val walletInfoBackground: Color,
    val walletInfoBackgroundBorder: Color,
    val beldexAddressBackground: Color,
    val receiveCardBackground: Color,
    val qrCodeBackground: Color,
    val errorMessageColor: Color,
    val textFiledBorderColor: Color,
    val totalBalanceColor: Color,
    val textHint: Color,
    val dividerColor: Color,
    val popUpAddressBackground: Color,
    val walletDashboardShowBalanceCardBackground: Color,
    val walletDashboardMainMenuCardBackground: Color,
    val walletDashboardQRButtonBackground: Color,
    val walletDashboardSendButtonBackground: Color,
    val walletDashboardReceiveButtonBackground: Color,
    val walletDashboardRescanButtonBackground: Color,
    val transactionFilterBackground: Color,
    val transactionFilterIcon: Color,
    val transactionHistoryCardBackground: Color,
    val walletSyncingIcon: Color,
    val walletSyncingSubTitle: Color,
    val transactionTypeTitle: Color,
    val transactionHistoryCardDivider: Color,
    val transactionDateTitle: Color,
    val transactionSubTitle: Color,
    val transactionHistoryArrowForwardIconColor: Color,
    val transactionHistoryArrowBackIconColor: Color,
    val copyIcon: Color,
    val selectDateRangeText: Color,
    val cancelButtonColor: Color,
    val secondaryColor: Color,
    val currentBlockHeightContainerBackground: Color,
    val addNodeHintColor : Color,
    val disableButtonContentColor : Color,
    val transactionFilterEnableColor : Color,
    val disableDateColor : Color,
    val iconBackground: Color,
    val clearColor: Color,
    val cancelColor: Color,
    val loaderBackground: Color,
    val callBottomBackground: Color,
    val circularProgressBarBackground : Color,
    val disablePrimaryButtonContent : Color,
    val noAddressIcon : Color,
    val numberPickerDivider: Color,
    val optionalTextfieldBackground: Color,
    val clearDataSubTitle: Color,
    val textSelectionColor: Color,
    val disabledNextButtonColor : Color,
    val disableWalletButtonColor : Color,
    val disableWalletButtonContentColor : Color,
    val listItemBackground : Color,
    val bnsDialogBackground: Color,
    val linkBnsCancelButtonContent: Color,
    val linkBnsDisabledButtonContent: Color,
    val linkBnsAddressBackground: Color,
    val profileAddressCardBackground: Color,
    val profileCameraIconBackgroundWithBnsTag: Color,
    val profileCameraIconBackground: Color
)

val lightColors = Colors(
    primaryButtonColor = Color(0xFF00BD40),
    secondaryButtonColor = Color(0xFFEFEFEF),
    backgroundColor = Color(0xFFEBEBEB),
    secondaryContentColor = Color(0xFF333333),
    editTextPlaceholder = Color(0xFFA7A7BA),
    textFieldFocusedColor = Color(0xFF00BD40),
    textFieldUnfocusedColor = Color(0xFFA7A7BA),
    textFieldCursorColor = Color(0x66222222),
    textFieldTextColor = Color(0xFF333333),
    tertiaryButtonColor = Color(0xFF0085FF),
    disabledPrimaryButtonContentColor = Color(0xFFF8F8F8),
    onMainContainerTextColor = Color(0xFF333333),
    secondaryTextColor = Color(0xFF8A8A9D),
    editTextBackground = Color(0xFFF8F8F8),
    editTextColor = Color(0xFF333333),
    editTextHint = Color(0xFFA7A7BA),
    titleTextColor = Color(0xFF333333),
    iconColor = Color(0xFF717194),
    beldexAddressColor = Color(0xFF00A3FF),
    cardBackground = Color(0xFFFFFFFF),
    iconTint = Color(0xFF333333),
    changeLogColor = Color(0xFF333333),
    changeLogBackground = Color(0xFFF4F4F4),
    lockTimerColor = Color(0xFF8A8A9D),
    unCheckedSwitchThumb = Color(0xFFA7A7BA),
    switchTrackColor = Color.White,
    settingsCardBackground = Color(0xFFF4F4F4),
    dialogBackground = Color(0xFFF8F8F8),
    restoreDescColor = Color(0xFFACACAC),
    seedInfoTextColor = Color(0xFFECAB0F),
    actionIconBackground = Color(0xFFFFFFFF),
    createButtonBackground = Color(0xFFF8F8F8),
    contactCardBackground = Color(0xFFECECEC),
    contactCardBorder = Color(0xFFA7A7BA),
    requestCountBackground = Color(0xFFFFFFFF),
    requestCountColor = Color(0xFF1C1C26),
    searchBackground = Color(0xFFF8F8F8),
    inputHintColor = Color(0xFF8D8D8D),
    disabledButtonContainerColor = Color(0xFFF8F8F8),
    disabledButtonContent = Color(0xFF6E6E7C),
    textFieldDescriptionColor = Color(0xFF333333),
    cancelButtonTextColor = Color(0xFF8A8A9D),
    textColor = Color(0xFF111111),
    walletInfoHighlightColor = Color(0xFF00C304),
    walletInfoBackground = Color(0xFFFFFFFF),
    walletInfoBackgroundBorder = Color(0xFF111119),
    beldexAddressBackground = Color(0xFFF8F8F8),
    receiveCardBackground = Color(0xFFEBEBEB),
    qrCodeBackground = Color(0xFFF8F8F8),
    errorMessageColor = Color(0xFFF6402C),
    textFiledBorderColor = Color(0xFFA7A7BA),
    totalBalanceColor = Color(0xFFACACAC),
    textHint = Color(0xFFA7A7BA),
    dividerColor = Color(0XFFA7A7BA),
    popUpAddressBackground = Color(0xFFF8F8F8),
    walletDashboardShowBalanceCardBackground = Color(0xffFFFFFF),
    walletDashboardMainMenuCardBackground = Color(0xffF0F0F0),
    walletDashboardQRButtonBackground = Color(0xffFFFFFF),
    walletDashboardSendButtonBackground = Color(0xff2979FB),
    walletDashboardReceiveButtonBackground = Color(0xff00BD40),
    walletDashboardRescanButtonBackground = Color(0xffE0E0E0),
    transactionFilterBackground = Color(0xff333333),
    transactionFilterIcon = Color(0xffFFFFFF),
    transactionHistoryCardBackground = Color(0xffEBEBEB),
    walletSyncingIcon = Color(0xffA7A7BA),
    walletSyncingSubTitle = Color(0xff82828D),
    transactionTypeTitle = Color(0xff82828D),
    transactionHistoryCardDivider = Color(0xffA7A7BA),
    transactionDateTitle = Color(0xff333333),
    transactionSubTitle = Color(0xff82828D),
    transactionHistoryArrowForwardIconColor = Color(0xff717194),
    transactionHistoryArrowBackIconColor = Color(0xff333333),
    copyIcon = Color(0xff00BD40),
    selectDateRangeText = Color(0xff222222),
    cancelButtonColor = Color(0xffECECEC),
    secondaryColor = Color(0xff2929FB),
    currentBlockHeightContainerBackground = Color(0xffF8F8F8),
    addNodeHintColor = Color(0xFFA7A7BA),
    disableButtonContentColor = Color(0xffA7A7BA),
    transactionFilterEnableColor = Color(0xffA7A7BA),
    disableDateColor = Color(0xffA7A7BA),
    iconBackground = Color(0xFFE0E0E0),
    clearColor = Color(0xFFFF3E3E),
    cancelColor = Color(0xFFACACAC),
    loaderBackground = Color(0xA4000000),
    callBottomBackground = Color(0xFFE8E8E8),
    circularProgressBarBackground = Color(0xffEBEBEB),
    disablePrimaryButtonContent = Color(0xFF8A8A9D),
    noAddressIcon = Color(0xffA3A3B2),
    numberPickerDivider = Color(0xFFA7A7BA),
    optionalTextfieldBackground = Color(0xFFF4F4F4),
    clearDataSubTitle = Color(0XFF6A6A77),
    textSelectionColor= Color(0xFF008D06),
    disabledNextButtonColor = Color(0xFFA7A7BA),
    disableWalletButtonColor = Color(0xFFE0E0E0),
    disableWalletButtonContentColor = Color(0xFF000000),
    listItemBackground = Color(0xFFF8F8F8),
    bnsDialogBackground = Color(0xFFEBEBEB),
    linkBnsCancelButtonContent = Color(0xFF6C6C78),
    linkBnsDisabledButtonContent = Color(0xFFACACAC),
    linkBnsAddressBackground = Color(0xFFECECEC),
    profileAddressCardBackground = Color(0xFFFFFFFF),
    profileCameraIconBackgroundWithBnsTag = Color(0xFFEBEBEB),
    profileCameraIconBackground = Color(0xFFF8F8F8)
)

val darkColors = Colors(
    primaryButtonColor = Color(0xFF00BD40),
    secondaryButtonColor = Color(0xFF282836),
    backgroundColor = Color(0xFF11111A),
    secondaryContentColor = Color(0xFFFFFFFF),
    editTextPlaceholder = Color(0xFFA7A7BA),
    textFieldFocusedColor = Color(0xFF00BD40),
    textFieldUnfocusedColor = Color(0xFF4B4B64),
    textFieldCursorColor = Color(0x66FFFFFF),
    textFieldTextColor = Color(0x80FFFFFF),
    tertiaryButtonColor = Color(0xFF0085FF),
    disabledPrimaryButtonContentColor = Color(0xFF6C6C78),
    onMainContainerTextColor = Color(0xFFFFFFFF),
    secondaryTextColor = Color(0xFFA7A7BA),
    editTextBackground = Color(0xFF1C1C26),
    editTextColor = Color(0xFFEBEBEB),
    editTextHint = Color(0xFFA7A7BA),
    titleTextColor = Color(0xFFEBEBEB),
    iconColor = Color(0xFF717194),
    beldexAddressColor = Color(0xFF00A3FF),
    cardBackground = Color(0xFF282836),
    iconTint = Color(0xFFFFFFFF),
    changeLogColor = Color(0xFFEBEBEB),
    changeLogBackground = Color.Transparent,
    lockTimerColor = Color(0xFFACACAC),
    unCheckedSwitchThumb = Color(0xFF9595B5),
    switchTrackColor = Color(0xFF363645),
    settingsCardBackground = Color(0xFF1C1C26),
    dialogBackground = Color(0xFF111119),
    restoreDescColor = Color(0xFFACACAC),
    seedInfoTextColor = Color(0xFFF0AF13),
    actionIconBackground = Color(0xFF2C2C3B),
    createButtonBackground = Color(0xFF11111A),
    contactCardBackground = Color(0xFF1C1C26),
    contactCardBorder = Color(0xFF353544),
    requestCountBackground = Color(0xFFEBEBEB),
    requestCountColor = Color(0xFF1C1C26),
    searchBackground = Color(0xFF282836),
    inputHintColor = Color(0xFFB9B9B9),
    disabledButtonContainerColor = Color(0xFF282836),
    disabledButtonContent = Color(0xFF6E6E7C),
    textFieldDescriptionColor = Color(0xFFA7A7BA),
    cancelButtonTextColor = Color(0xFFACACAC),
    textColor = Color(0xFFFFFFFF),
    walletInfoHighlightColor = Color(0xFF00C304),
    walletInfoBackground = Color(0xFF111119),
    walletInfoBackgroundBorder = Color(0xFF24242F),
    beldexAddressBackground = Color(0xFF1C1C26),
    receiveCardBackground = Color(0xFF111119),
    qrCodeBackground = Color(0xFF2C2C3B),
    errorMessageColor = Color(0xFFF6402C),
    textFiledBorderColor = Color(0xFF4B4B64),
    totalBalanceColor = Color(0xFFACACAC),
    textHint = Color(0xFFA7A7BA),
    dividerColor = Color(0XFF4B4B64),
    popUpAddressBackground = Color(0xFF282836),
    walletDashboardShowBalanceCardBackground = Color(0xff2B2B3A),
    walletDashboardMainMenuCardBackground = Color(0xff1C1C26),
    walletDashboardQRButtonBackground = Color(0xffEBEBEB),
    walletDashboardSendButtonBackground = Color(0xff2979FB),
    walletDashboardReceiveButtonBackground = Color(0xff00BD40),
    walletDashboardRescanButtonBackground = Color(0xff333343),
    transactionFilterBackground = Color(0xffEBEBEB),
    transactionFilterIcon = Color(0xff1C1C26),
    transactionHistoryCardBackground = Color(0xff11111A),
    walletSyncingIcon = Color(0xff65656E),
    walletSyncingSubTitle = Color(0xff82828D),
    transactionTypeTitle = Color(0xffACACAC),
    transactionHistoryCardDivider = Color(0xff4B4B64),
    transactionDateTitle = Color(0xffFFFFFF),
    transactionSubTitle = Color(0xffA7A7BA),
    transactionHistoryArrowForwardIconColor = Color(0xff717194),
    transactionHistoryArrowBackIconColor = Color(0xffFFFFFF),
    copyIcon = Color(0xff00BD40),
    selectDateRangeText = Color(0xffFFFFFF),
    cancelButtonColor = Color(0xff1C1C26),
    secondaryColor = Color(0xff2929FB),
    currentBlockHeightContainerBackground = Color(0xff1C1C26),
    addNodeHintColor = Color(0xFF77778B),
    disableButtonContentColor = Color(0xffA7A7BA),
    transactionFilterEnableColor = Color(0xffACACAC),
    disableDateColor = Color(0xff333343),
    iconBackground = Color(0xFF30303F),
    clearColor = Color(0xFFFF3E3E),
    cancelColor = Color(0xFFACACAC),
    loaderBackground = Color(0xA4000000),
    callBottomBackground = Color(0xFF11111A),
    circularProgressBarBackground = Color(0xff30303F),
    disablePrimaryButtonContent = Color(0xFF6C6C78),
    noAddressIcon = Color(0xff65656E),
    numberPickerDivider = Color(0xFF4B4B64),
    optionalTextfieldBackground = Color(0xFF1C1C26),
    clearDataSubTitle = Color(0XFF6A6A77),
    textSelectionColor= Color(0xFF008D06),
    disabledNextButtonColor = Color(0xFF6C6C78),
    disableWalletButtonColor = Color(0xFF333343),
    disableWalletButtonContentColor = Color(0xFF000000),
    listItemBackground = Color(0xFF1C1C26),
    bnsDialogBackground = Color(0xFF282836),
    linkBnsCancelButtonContent = Color(0xFFACACAC),
    linkBnsDisabledButtonContent = Color(0xFF6C6C78),
    linkBnsAddressBackground = Color(0xFF282836),
    profileAddressCardBackground = Color(0xFF11111A),
    profileCameraIconBackgroundWithBnsTag = Color(0xFF11111A),
    profileCameraIconBackground = Color(0xFF111119)
)



val LocalAppColors = staticCompositionLocalOf {
    darkColors
}

val MaterialTheme.appColors: Colors
    @Composable
    get() = LocalAppColors.current