// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebRtcData.proto

package io.beldex.bchat.webrtc;

public final class WebRtcDataProtos {
  private WebRtcDataProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConnectedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signal.Connected)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>optional uint64 id = 1;</code>
     * @return The id.
     */
    long getId();
  }
  /**
   * Protobuf type {@code signal.Connected}
   */
  public static final class Connected extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:signal.Connected)
      ConnectedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Connected.newBuilder() to construct.
    private Connected(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Connected() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Connected();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Connected_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Connected_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.class, io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>optional uint64 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.beldex.bchat.webrtc.WebRtcDataProtos.Connected)) {
        return super.equals(obj);
      }
      io.beldex.bchat.webrtc.WebRtcDataProtos.Connected other = (io.beldex.bchat.webrtc.WebRtcDataProtos.Connected) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Connected parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Connected parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Connected parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Connected parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Connected parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Connected parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Connected parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Connected parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Connected parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Connected parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Connected parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Connected parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.beldex.bchat.webrtc.WebRtcDataProtos.Connected prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signal.Connected}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:signal.Connected)
        io.beldex.bchat.webrtc.WebRtcDataProtos.ConnectedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Connected_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Connected_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.class, io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.Builder.class);
      }

      // Construct using io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Connected_descriptor;
      }

      @java.lang.Override
      public io.beldex.bchat.webrtc.WebRtcDataProtos.Connected getDefaultInstanceForType() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.getDefaultInstance();
      }

      @java.lang.Override
      public io.beldex.bchat.webrtc.WebRtcDataProtos.Connected build() {
        io.beldex.bchat.webrtc.WebRtcDataProtos.Connected result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.beldex.bchat.webrtc.WebRtcDataProtos.Connected buildPartial() {
        io.beldex.bchat.webrtc.WebRtcDataProtos.Connected result = new io.beldex.bchat.webrtc.WebRtcDataProtos.Connected(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.beldex.bchat.webrtc.WebRtcDataProtos.Connected result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.beldex.bchat.webrtc.WebRtcDataProtos.Connected) {
          return mergeFrom((io.beldex.bchat.webrtc.WebRtcDataProtos.Connected)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.beldex.bchat.webrtc.WebRtcDataProtos.Connected other) {
        if (other == io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional uint64 id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:signal.Connected)
    }

    // @@protoc_insertion_point(class_scope:signal.Connected)
    private static final io.beldex.bchat.webrtc.WebRtcDataProtos.Connected DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.beldex.bchat.webrtc.WebRtcDataProtos.Connected();
    }

    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Connected getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Connected>
        PARSER = new com.google.protobuf.AbstractParser<Connected>() {
      @java.lang.Override
      public Connected parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Connected> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Connected> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.beldex.bchat.webrtc.WebRtcDataProtos.Connected getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HangupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signal.Hangup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>optional uint64 id = 1;</code>
     * @return The id.
     */
    long getId();
  }
  /**
   * Protobuf type {@code signal.Hangup}
   */
  public static final class Hangup extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:signal.Hangup)
      HangupOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Hangup.newBuilder() to construct.
    private Hangup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Hangup() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Hangup();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Hangup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Hangup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.class, io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>optional uint64 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup)) {
        return super.equals(obj);
      }
      io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup other = (io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signal.Hangup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:signal.Hangup)
        io.beldex.bchat.webrtc.WebRtcDataProtos.HangupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Hangup_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Hangup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.class, io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.Builder.class);
      }

      // Construct using io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Hangup_descriptor;
      }

      @java.lang.Override
      public io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup getDefaultInstanceForType() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.getDefaultInstance();
      }

      @java.lang.Override
      public io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup build() {
        io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup buildPartial() {
        io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup result = new io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup) {
          return mergeFrom((io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup other) {
        if (other == io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional uint64 id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:signal.Hangup)
    }

    // @@protoc_insertion_point(class_scope:signal.Hangup)
    private static final io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup();
    }

    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Hangup>
        PARSER = new com.google.protobuf.AbstractParser<Hangup>() {
      @java.lang.Override
      public Hangup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Hangup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hangup> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VideoStreamingStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signal.VideoStreamingStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>optional uint64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>optional bool enabled = 2;</code>
     * @return Whether the enabled field is set.
     */
    boolean hasEnabled();
    /**
     * <code>optional bool enabled = 2;</code>
     * @return The enabled.
     */
    boolean getEnabled();
  }
  /**
   * Protobuf type {@code signal.VideoStreamingStatus}
   */
  public static final class VideoStreamingStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:signal.VideoStreamingStatus)
      VideoStreamingStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VideoStreamingStatus.newBuilder() to construct.
    private VideoStreamingStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VideoStreamingStatus() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VideoStreamingStatus();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_VideoStreamingStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_VideoStreamingStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.class, io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>optional uint64 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int ENABLED_FIELD_NUMBER = 2;
    private boolean enabled_ = false;
    /**
     * <code>optional bool enabled = 2;</code>
     * @return Whether the enabled field is set.
     */
    @java.lang.Override
    public boolean hasEnabled() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bool enabled = 2;</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return enabled_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(2, enabled_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, enabled_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus)) {
        return super.equals(obj);
      }
      io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus other = (io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasEnabled() != other.hasEnabled()) return false;
      if (hasEnabled()) {
        if (getEnabled()
            != other.getEnabled()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasEnabled()) {
        hash = (37 * hash) + ENABLED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getEnabled());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signal.VideoStreamingStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:signal.VideoStreamingStatus)
        io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_VideoStreamingStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_VideoStreamingStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.class, io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.Builder.class);
      }

      // Construct using io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        enabled_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_VideoStreamingStatus_descriptor;
      }

      @java.lang.Override
      public io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus getDefaultInstanceForType() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.getDefaultInstance();
      }

      @java.lang.Override
      public io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus build() {
        io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus buildPartial() {
        io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus result = new io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.enabled_ = enabled_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus) {
          return mergeFrom((io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus other) {
        if (other == io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEnabled()) {
          setEnabled(other.getEnabled());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                enabled_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional uint64 id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private boolean enabled_ ;
      /**
       * <code>optional bool enabled = 2;</code>
       * @return Whether the enabled field is set.
       */
      @java.lang.Override
      public boolean hasEnabled() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bool enabled = 2;</code>
       * @return The enabled.
       */
      @java.lang.Override
      public boolean getEnabled() {
        return enabled_;
      }
      /**
       * <code>optional bool enabled = 2;</code>
       * @param value The enabled to set.
       * @return This builder for chaining.
       */
      public Builder setEnabled(boolean value) {

        enabled_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool enabled = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnabled() {
        bitField0_ = (bitField0_ & ~0x00000002);
        enabled_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:signal.VideoStreamingStatus)
    }

    // @@protoc_insertion_point(class_scope:signal.VideoStreamingStatus)
    private static final io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus();
    }

    public static io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<VideoStreamingStatus>
        PARSER = new com.google.protobuf.AbstractParser<VideoStreamingStatus>() {
      @java.lang.Override
      public VideoStreamingStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VideoStreamingStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VideoStreamingStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signal.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .signal.Connected connected = 1;</code>
     * @return Whether the connected field is set.
     */
    boolean hasConnected();
    /**
     * <code>optional .signal.Connected connected = 1;</code>
     * @return The connected.
     */
    io.beldex.bchat.webrtc.WebRtcDataProtos.Connected getConnected();
    /**
     * <code>optional .signal.Connected connected = 1;</code>
     */
    io.beldex.bchat.webrtc.WebRtcDataProtos.ConnectedOrBuilder getConnectedOrBuilder();

    /**
     * <code>optional .signal.Hangup hangup = 2;</code>
     * @return Whether the hangup field is set.
     */
    boolean hasHangup();
    /**
     * <code>optional .signal.Hangup hangup = 2;</code>
     * @return The hangup.
     */
    io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup getHangup();
    /**
     * <code>optional .signal.Hangup hangup = 2;</code>
     */
    io.beldex.bchat.webrtc.WebRtcDataProtos.HangupOrBuilder getHangupOrBuilder();

    /**
     * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
     * @return Whether the videoStreamingStatus field is set.
     */
    boolean hasVideoStreamingStatus();
    /**
     * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
     * @return The videoStreamingStatus.
     */
    io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus getVideoStreamingStatus();
    /**
     * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
     */
    io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatusOrBuilder getVideoStreamingStatusOrBuilder();
  }
  /**
   * Protobuf type {@code signal.Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:signal.Data)
      DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Data();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Data_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.beldex.bchat.webrtc.WebRtcDataProtos.Data.class, io.beldex.bchat.webrtc.WebRtcDataProtos.Data.Builder.class);
    }

    private int bitField0_;
    public static final int CONNECTED_FIELD_NUMBER = 1;
    private io.beldex.bchat.webrtc.WebRtcDataProtos.Connected connected_;
    /**
     * <code>optional .signal.Connected connected = 1;</code>
     * @return Whether the connected field is set.
     */
    @java.lang.Override
    public boolean hasConnected() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .signal.Connected connected = 1;</code>
     * @return The connected.
     */
    @java.lang.Override
    public io.beldex.bchat.webrtc.WebRtcDataProtos.Connected getConnected() {
      return connected_ == null ? io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.getDefaultInstance() : connected_;
    }
    /**
     * <code>optional .signal.Connected connected = 1;</code>
     */
    @java.lang.Override
    public io.beldex.bchat.webrtc.WebRtcDataProtos.ConnectedOrBuilder getConnectedOrBuilder() {
      return connected_ == null ? io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.getDefaultInstance() : connected_;
    }

    public static final int HANGUP_FIELD_NUMBER = 2;
    private io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup hangup_;
    /**
     * <code>optional .signal.Hangup hangup = 2;</code>
     * @return Whether the hangup field is set.
     */
    @java.lang.Override
    public boolean hasHangup() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .signal.Hangup hangup = 2;</code>
     * @return The hangup.
     */
    @java.lang.Override
    public io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup getHangup() {
      return hangup_ == null ? io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.getDefaultInstance() : hangup_;
    }
    /**
     * <code>optional .signal.Hangup hangup = 2;</code>
     */
    @java.lang.Override
    public io.beldex.bchat.webrtc.WebRtcDataProtos.HangupOrBuilder getHangupOrBuilder() {
      return hangup_ == null ? io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.getDefaultInstance() : hangup_;
    }

    public static final int VIDEOSTREAMINGSTATUS_FIELD_NUMBER = 3;
    private io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus videoStreamingStatus_;
    /**
     * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
     * @return Whether the videoStreamingStatus field is set.
     */
    @java.lang.Override
    public boolean hasVideoStreamingStatus() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
     * @return The videoStreamingStatus.
     */
    @java.lang.Override
    public io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus getVideoStreamingStatus() {
      return videoStreamingStatus_ == null ? io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.getDefaultInstance() : videoStreamingStatus_;
    }
    /**
     * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
     */
    @java.lang.Override
    public io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatusOrBuilder getVideoStreamingStatusOrBuilder() {
      return videoStreamingStatus_ == null ? io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.getDefaultInstance() : videoStreamingStatus_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getConnected());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getHangup());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getVideoStreamingStatus());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getConnected());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getHangup());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getVideoStreamingStatus());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.beldex.bchat.webrtc.WebRtcDataProtos.Data)) {
        return super.equals(obj);
      }
      io.beldex.bchat.webrtc.WebRtcDataProtos.Data other = (io.beldex.bchat.webrtc.WebRtcDataProtos.Data) obj;

      if (hasConnected() != other.hasConnected()) return false;
      if (hasConnected()) {
        if (!getConnected()
            .equals(other.getConnected())) return false;
      }
      if (hasHangup() != other.hasHangup()) return false;
      if (hasHangup()) {
        if (!getHangup()
            .equals(other.getHangup())) return false;
      }
      if (hasVideoStreamingStatus() != other.hasVideoStreamingStatus()) return false;
      if (hasVideoStreamingStatus()) {
        if (!getVideoStreamingStatus()
            .equals(other.getVideoStreamingStatus())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasConnected()) {
        hash = (37 * hash) + CONNECTED_FIELD_NUMBER;
        hash = (53 * hash) + getConnected().hashCode();
      }
      if (hasHangup()) {
        hash = (37 * hash) + HANGUP_FIELD_NUMBER;
        hash = (53 * hash) + getHangup().hashCode();
      }
      if (hasVideoStreamingStatus()) {
        hash = (37 * hash) + VIDEOSTREAMINGSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + getVideoStreamingStatus().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.beldex.bchat.webrtc.WebRtcDataProtos.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signal.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:signal.Data)
        io.beldex.bchat.webrtc.WebRtcDataProtos.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Data_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.beldex.bchat.webrtc.WebRtcDataProtos.Data.class, io.beldex.bchat.webrtc.WebRtcDataProtos.Data.Builder.class);
      }

      // Construct using io.beldex.bchat.webrtc.WebRtcDataProtos.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getConnectedFieldBuilder();
          getHangupFieldBuilder();
          getVideoStreamingStatusFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        connected_ = null;
        if (connectedBuilder_ != null) {
          connectedBuilder_.dispose();
          connectedBuilder_ = null;
        }
        hangup_ = null;
        if (hangupBuilder_ != null) {
          hangupBuilder_.dispose();
          hangupBuilder_ = null;
        }
        videoStreamingStatus_ = null;
        if (videoStreamingStatusBuilder_ != null) {
          videoStreamingStatusBuilder_.dispose();
          videoStreamingStatusBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.internal_static_signal_Data_descriptor;
      }

      @java.lang.Override
      public io.beldex.bchat.webrtc.WebRtcDataProtos.Data getDefaultInstanceForType() {
        return io.beldex.bchat.webrtc.WebRtcDataProtos.Data.getDefaultInstance();
      }

      @java.lang.Override
      public io.beldex.bchat.webrtc.WebRtcDataProtos.Data build() {
        io.beldex.bchat.webrtc.WebRtcDataProtos.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.beldex.bchat.webrtc.WebRtcDataProtos.Data buildPartial() {
        io.beldex.bchat.webrtc.WebRtcDataProtos.Data result = new io.beldex.bchat.webrtc.WebRtcDataProtos.Data(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.beldex.bchat.webrtc.WebRtcDataProtos.Data result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.connected_ = connectedBuilder_ == null
              ? connected_
              : connectedBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.hangup_ = hangupBuilder_ == null
              ? hangup_
              : hangupBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.videoStreamingStatus_ = videoStreamingStatusBuilder_ == null
              ? videoStreamingStatus_
              : videoStreamingStatusBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.beldex.bchat.webrtc.WebRtcDataProtos.Data) {
          return mergeFrom((io.beldex.bchat.webrtc.WebRtcDataProtos.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.beldex.bchat.webrtc.WebRtcDataProtos.Data other) {
        if (other == io.beldex.bchat.webrtc.WebRtcDataProtos.Data.getDefaultInstance()) return this;
        if (other.hasConnected()) {
          mergeConnected(other.getConnected());
        }
        if (other.hasHangup()) {
          mergeHangup(other.getHangup());
        }
        if (other.hasVideoStreamingStatus()) {
          mergeVideoStreamingStatus(other.getVideoStreamingStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getConnectedFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getHangupFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getVideoStreamingStatusFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private io.beldex.bchat.webrtc.WebRtcDataProtos.Connected connected_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.beldex.bchat.webrtc.WebRtcDataProtos.Connected, io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.Builder, io.beldex.bchat.webrtc.WebRtcDataProtos.ConnectedOrBuilder> connectedBuilder_;
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       * @return Whether the connected field is set.
       */
      public boolean hasConnected() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       * @return The connected.
       */
      public io.beldex.bchat.webrtc.WebRtcDataProtos.Connected getConnected() {
        if (connectedBuilder_ == null) {
          return connected_ == null ? io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.getDefaultInstance() : connected_;
        } else {
          return connectedBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      public Builder setConnected(io.beldex.bchat.webrtc.WebRtcDataProtos.Connected value) {
        if (connectedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          connected_ = value;
        } else {
          connectedBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      public Builder setConnected(
          io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.Builder builderForValue) {
        if (connectedBuilder_ == null) {
          connected_ = builderForValue.build();
        } else {
          connectedBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      public Builder mergeConnected(io.beldex.bchat.webrtc.WebRtcDataProtos.Connected value) {
        if (connectedBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            connected_ != null &&
            connected_ != io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.getDefaultInstance()) {
            getConnectedBuilder().mergeFrom(value);
          } else {
            connected_ = value;
          }
        } else {
          connectedBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      public Builder clearConnected() {
        bitField0_ = (bitField0_ & ~0x00000001);
        connected_ = null;
        if (connectedBuilder_ != null) {
          connectedBuilder_.dispose();
          connectedBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      public io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.Builder getConnectedBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getConnectedFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      public io.beldex.bchat.webrtc.WebRtcDataProtos.ConnectedOrBuilder getConnectedOrBuilder() {
        if (connectedBuilder_ != null) {
          return connectedBuilder_.getMessageOrBuilder();
        } else {
          return connected_ == null ?
              io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.getDefaultInstance() : connected_;
        }
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.beldex.bchat.webrtc.WebRtcDataProtos.Connected, io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.Builder, io.beldex.bchat.webrtc.WebRtcDataProtos.ConnectedOrBuilder> 
          getConnectedFieldBuilder() {
        if (connectedBuilder_ == null) {
          connectedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.beldex.bchat.webrtc.WebRtcDataProtos.Connected, io.beldex.bchat.webrtc.WebRtcDataProtos.Connected.Builder, io.beldex.bchat.webrtc.WebRtcDataProtos.ConnectedOrBuilder>(
                  getConnected(),
                  getParentForChildren(),
                  isClean());
          connected_ = null;
        }
        return connectedBuilder_;
      }

      private io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup hangup_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup, io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.Builder, io.beldex.bchat.webrtc.WebRtcDataProtos.HangupOrBuilder> hangupBuilder_;
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       * @return Whether the hangup field is set.
       */
      public boolean hasHangup() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       * @return The hangup.
       */
      public io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup getHangup() {
        if (hangupBuilder_ == null) {
          return hangup_ == null ? io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.getDefaultInstance() : hangup_;
        } else {
          return hangupBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      public Builder setHangup(io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup value) {
        if (hangupBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hangup_ = value;
        } else {
          hangupBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      public Builder setHangup(
          io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.Builder builderForValue) {
        if (hangupBuilder_ == null) {
          hangup_ = builderForValue.build();
        } else {
          hangupBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      public Builder mergeHangup(io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup value) {
        if (hangupBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            hangup_ != null &&
            hangup_ != io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.getDefaultInstance()) {
            getHangupBuilder().mergeFrom(value);
          } else {
            hangup_ = value;
          }
        } else {
          hangupBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      public Builder clearHangup() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hangup_ = null;
        if (hangupBuilder_ != null) {
          hangupBuilder_.dispose();
          hangupBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      public io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.Builder getHangupBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHangupFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      public io.beldex.bchat.webrtc.WebRtcDataProtos.HangupOrBuilder getHangupOrBuilder() {
        if (hangupBuilder_ != null) {
          return hangupBuilder_.getMessageOrBuilder();
        } else {
          return hangup_ == null ?
              io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.getDefaultInstance() : hangup_;
        }
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup, io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.Builder, io.beldex.bchat.webrtc.WebRtcDataProtos.HangupOrBuilder> 
          getHangupFieldBuilder() {
        if (hangupBuilder_ == null) {
          hangupBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup, io.beldex.bchat.webrtc.WebRtcDataProtos.Hangup.Builder, io.beldex.bchat.webrtc.WebRtcDataProtos.HangupOrBuilder>(
                  getHangup(),
                  getParentForChildren(),
                  isClean());
          hangup_ = null;
        }
        return hangupBuilder_;
      }

      private io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus videoStreamingStatus_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus, io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.Builder, io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatusOrBuilder> videoStreamingStatusBuilder_;
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       * @return Whether the videoStreamingStatus field is set.
       */
      public boolean hasVideoStreamingStatus() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       * @return The videoStreamingStatus.
       */
      public io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus getVideoStreamingStatus() {
        if (videoStreamingStatusBuilder_ == null) {
          return videoStreamingStatus_ == null ? io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.getDefaultInstance() : videoStreamingStatus_;
        } else {
          return videoStreamingStatusBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      public Builder setVideoStreamingStatus(io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus value) {
        if (videoStreamingStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          videoStreamingStatus_ = value;
        } else {
          videoStreamingStatusBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      public Builder setVideoStreamingStatus(
          io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.Builder builderForValue) {
        if (videoStreamingStatusBuilder_ == null) {
          videoStreamingStatus_ = builderForValue.build();
        } else {
          videoStreamingStatusBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      public Builder mergeVideoStreamingStatus(io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus value) {
        if (videoStreamingStatusBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            videoStreamingStatus_ != null &&
            videoStreamingStatus_ != io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.getDefaultInstance()) {
            getVideoStreamingStatusBuilder().mergeFrom(value);
          } else {
            videoStreamingStatus_ = value;
          }
        } else {
          videoStreamingStatusBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      public Builder clearVideoStreamingStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        videoStreamingStatus_ = null;
        if (videoStreamingStatusBuilder_ != null) {
          videoStreamingStatusBuilder_.dispose();
          videoStreamingStatusBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      public io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.Builder getVideoStreamingStatusBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getVideoStreamingStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      public io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatusOrBuilder getVideoStreamingStatusOrBuilder() {
        if (videoStreamingStatusBuilder_ != null) {
          return videoStreamingStatusBuilder_.getMessageOrBuilder();
        } else {
          return videoStreamingStatus_ == null ?
              io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.getDefaultInstance() : videoStreamingStatus_;
        }
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus, io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.Builder, io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatusOrBuilder> 
          getVideoStreamingStatusFieldBuilder() {
        if (videoStreamingStatusBuilder_ == null) {
          videoStreamingStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus, io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatus.Builder, io.beldex.bchat.webrtc.WebRtcDataProtos.VideoStreamingStatusOrBuilder>(
                  getVideoStreamingStatus(),
                  getParentForChildren(),
                  isClean());
          videoStreamingStatus_ = null;
        }
        return videoStreamingStatusBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:signal.Data)
    }

    // @@protoc_insertion_point(class_scope:signal.Data)
    private static final io.beldex.bchat.webrtc.WebRtcDataProtos.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.beldex.bchat.webrtc.WebRtcDataProtos.Data();
    }

    public static io.beldex.bchat.webrtc.WebRtcDataProtos.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      @java.lang.Override
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.beldex.bchat.webrtc.WebRtcDataProtos.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_Connected_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_Connected_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_Hangup_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_Hangup_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_VideoStreamingStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_VideoStreamingStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020WebRtcData.proto\022\006signal\"\027\n\tConnected\022" +
      "\n\n\002id\030\001 \001(\004\"\024\n\006Hangup\022\n\n\002id\030\001 \001(\004\"3\n\024Vid" +
      "eoStreamingStatus\022\n\n\002id\030\001 \001(\004\022\017\n\007enabled" +
      "\030\002 \001(\010\"\210\001\n\004Data\022$\n\tconnected\030\001 \001(\0132\021.sig" +
      "nal.Connected\022\036\n\006hangup\030\002 \001(\0132\016.signal.H" +
      "angup\022:\n\024videoStreamingStatus\030\003 \001(\0132\034.si" +
      "gnal.VideoStreamingStatusB*\n\026io.beldex.b" +
      "chat.webrtcB\020WebRtcDataProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_signal_Connected_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_signal_Connected_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_Connected_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_signal_Hangup_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_signal_Hangup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_Hangup_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_signal_VideoStreamingStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_signal_VideoStreamingStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_VideoStreamingStatus_descriptor,
        new java.lang.String[] { "Id", "Enabled", });
    internal_static_signal_Data_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_signal_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_Data_descriptor,
        new java.lang.String[] { "Connected", "Hangup", "VideoStreamingStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
